spring:
  application:
    name: p81
  datasource:
    url: jdbc:postgresql://postgresql:5432/p81
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: public
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

server:
  error:
    include-exception: false
    include-message: always
    include-stacktrace: always

security:
  secret: ${JWT_SECRET:secret12345678}
  token-lifetime: 15m
  refresh-token-lifetime: 30d

logstash:
  url: logstash:4560

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include : "info,health,prometheus,metrics"
