name: Run Maven tests

on:
  push:
    branches:
      - 'main'
      - 'stable/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install common-lib
        run: sh mvn-install-commonlib.sh

      - name: Build with Maven
        run: mvn --batch-mode test